### ISSUE TITLE
Thank you, this worked like a dream

### ISSUE THREAD

**Issue by ewallace** [aoles/shinyURL#1]
Andrzej,
This is not an issue, this is a thank you. I was expecting it to talk all afternoon to get something functional for passing URLs around but with shinyURL it took 15 minutes. Many thanks for sharing a nice tool!
Edward

**Comment by aoles** [comment]
Hi Edward,
you're very welcome, many thanks for your kind words! I'm glad you find shinyURL useful in your project.

Cheers,
Andrzej
