### ISSUE TITLE
Question about navbar url in web server developed by shiny! Urgently!!!

### ISSUE THREAD

**Issue by Jianbo1991** [aoles/shinyURL#14]
My web server developed by shiny.  However I found that there are ****the same url****  when I choose the different navbar/tabpanel in my web server. Can someone help me please? It's difficult for me to solve this problem. I just need every different url when I choose different panel in my server.  Thank you very much!

**Comment by aoles** [comment]
Have you tried providing the `id` argument to `tabsetPanel` or `navbarPage` as advised in the [README](https://github.com/aoles/shinyURL/blob/master/README.md)?

**Comment by Jianbo1991** [comment]
Thank you very much! 
I used this code #navbarPage(id = "inTabset", "") , and input the code as following in my server.R
#server <- function(input, output, session) {
  observe({
    query <- parseQueryString(session$clientData$url_search)
   
    if (!is.null(query[['inTabset']])) {
      updateTabsetPanel(session, "inTabset", selected =  query[['inTabset']])
    }
 
  })
Then input "http://127.0.0.1:4541/?inTabset=xxx" in browser, then it could links to my panel in my web server.
